image: gitpod/workspace-java-21

tasks:
  - name: Build
    init: ./gradlew build -x test
    command: |
      echo "=== Drawing App Ready ==="
      echo "Run: ./gradlew run"
      echo "Or:  java -jar build/libs/drawing-app.jar"
      echo ""
      ./gradlew run --console=plain

vscode:
  extensions:
    - vscjava.vscode-java-pack
